[build]
  # No build process needed for static HTML
  publish = "."

[build.environment]
  # No environment variables needed

[[headers]]
  # Apply headers to all routes
  for = "/*"
  [headers.values]
    # Security headers
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Special cache settings for HTML files
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Special cache settings for images
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 404 redirect (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404 